### ISSUE TITLE
Issue while Training.

### ISSUE THREAD

**Issue by saimathura** [val-iisc/DeiT-LT#2]
Thank you for your great work on this project and for sharing the code with it. I used the code given to Train and tried to recreate the work. But there was a problem. As you can see the best numbers from my run which I have added here are not as good as the paper results. I don't know where I am making a mistake. 

```
BEST NUMBERS ----->
 ----------------Overall /  Head    /  Med      / Tail------------
AVERAGE:  52.04  /  70.333  /  52.0      /  29.379
--------CLS:   39.78 /   70.0     /  36.657  /  6.034
-------DIST:    40.1 /   36.25   /   41.829 /  42.759
raining time 11:58:40
```

I have also added my configuration here for you to refer to. I'm trying to recreate Cifar-100 with an imbalance score of 100:
I also used the provided teacher model to train:

```
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --use_env --master_port=47773 main.py \
    --model deit_base_distilled_patch16_224 \
    --batch-size 256 \
    --epochs 1200 \
    --gpu 0 \
    --teacher-path "/data/DeiT-LT/cifar100_paco_sam_if100.pth" \
    --distillation-type hard \
    --data-path cifar100 \
    --data-set CIFAR100LT \
    --imb_factor 0.01 \
    --output_dir deit_out_c100lt \
    --student-transform 0 \
    --teacher-transform 0 \
    --teacher-model resnet32 \
    --teacher-size 32 \
    --experiment [deitlt_paco_sam_cifar10_if100] \
    --drw 1100 \
    --no-mixup-drw \
    --custom_model \
    --accum-iter 4 \
    --save_freq 300 \
    --weighted-distillation \
    --moco-t 0.05 --moco-k 1024 --moco-dim 32 --feat_dim 64 --paco \
    --log-results \
```
when I do Eval I get this accuracy:
```
CURRENT NUMBERS ----->
Overall / Head / Med / Tail
AVERAGE:  54.72  /  72.833  /  55.4  /  31.414
CLS    :  43.34  /  73.722  /  41.571  /  7.759
DIST   :  42.6  /  39.639  /  45.257  /  43.069

```
But when I'm Training in the same setup I'm unable to reach the same accuracy.

Thank you in advance for your time and consideration.

**Comment by pradipto111** [comment]
Hi @saimathura , thanks for your interest in our work.

In order to reach optimal performance effective batch size sometimes plays an important role. 
Can you try the same training above with half the effective batch size? In essence, please use ```--batch-size 128``` for training on 2 GPUs and let us know what performance the model achieves.

Thanks.

**Comment by saimathura** [comment]
Ok sure, I will try doing that an get back to you.
