### ISSUE TITLE
class_map when running train_inat.sh

### ISSUE THREAD

**Issue by Jiejiegary** [val-iisc/DeiT-LT#3]
Thanks for your great work! When I run _train_inat.sh_, I find _class_map_ missing. Could you please help?

**Comment by pradipto111** [comment]
Hi @Jiejiegary 

Please uncomment `Line 383` to `Line 389` in `datasets.py` which calculates the `class_map` for INAT-2018.
The same has been updated in the latest commit.

Thanks for your interest in our work!
