### ISSUE TITLE
Training Results on CIFAR10 Dataset with an Imbalance Ratio of 100 Are Lower than the Performance Reported in the Paper

### ISSUE THREAD

**Issue by fantastice** [val-iisc/DeiT-LT#6]
Sure! Here’s the translation:

"Hello, I ran your code for 1200 epochs on the CIFAR10 dataset with an imbalance ratio of 100, but I found that the final results are lower than the data reported in the paper."
<img width="307" alt="图片1" src="https://github.com/user-attachments/assets/03edf2a2-cec2-40c5-a6cc-b657aa8382e9">

**Comment by pradipto111** [comment]
Hi @fantastice ,

Thanks for your interest in our work. This slight variation in numbers can be due to different precision variations, different GPU architecture, configurations even CUDA versions.

You may try running different seeds to achieve the best possible performance.

Best.

**Comment by fantastice** [comment]
Thank you very much,I will try more best.
